SELECT DISTINCT CC.CAR_ID FROM CAR_RENTAL_COMPANY_CAR CC
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON CC.CAR_ID = RH.CAR_ID
WHERE CC.CAR_TYPE = '세단' AND RH.START_DATE LIKE ('%-10-%')
ORDER BY CC.CAR_ID DESC